
  CREATE TABLE "ASIGNAR_MATERIAL" 
   (	"FMO_CODIGO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"SVO_CODIGO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"MTL_CODIGO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AML_CANTIDADESTIMADA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AML_CANTIDADUSADA" VARCHAR2(17 BYTE) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
