
  CREATE TABLE "SDS_LOCALIDADES_LCD" 
   (	"LCD_CODIGO" VARCHAR2(7 BYTE) NOT NULL ENABLE, 
	"CTR_ANO_FISCAL" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"CTR_ID_CENTRO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PSO_CODIGO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"EDO_CODIGO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"LCD_NOMBRE" VARCHAR2(15 BYTE) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
