
  CREATE TABLE "SDS_TIPO_MATERIALES_MTL" 
   (	"MTL_CODIGO" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"TML_CODIGO" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"MTL_NOMBRE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"MTL_CANTIDAD" VARCHAR2(5 BYTE) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
