
  CREATE TABLE "SDS_FORMATOS_FMO" 
   (	"FMO_CODIGO" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"JEF_INFA_PERN_TIPN_CODIGO" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"JEF_INFA_NACIONALIDAD" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"JEF_INFA_CEDULA" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"JEF_INFA_CTR_ID_CENTRO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"JEF_INFA_CTR_ANO_FISCAL" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"FMO_FECHA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"JEF_FECHA_INI" VARCHAR2(20 BYTE) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
