
  CREATE TABLE "SIF_CENTRO_COSTOS" 
   (	"CTR_ANO_FISCAL" VARCHAR2(4 BYTE), 
	"CTR_ID_CENTRO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CTR_DESCRIPCION" VARCHAR2(100 BYTE), 
	"CTR_SUB_CODIGO" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"CTR_UBICACION" VARCHAR2(50 BYTE), 
	"CTR_TELEFONO1" VARCHAR2(12 BYTE), 
	"CTR_TELEFONO2" VARCHAR2(12 BYTE), 
	"CTR_CORREO_ELECT" VARCHAR2(50 BYTE), 
	"CTR_CREADO_POR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CTR_MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"CTR_FECHA_UPDATE" DATE NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
